graph TD
    subgraph "Table 1"
    PK1["PK: (C1, C2)"] --> C3
    end

    subgraph "Table 2"
    PK2["PK: C1"] --> C8
    end

    subgraph "Table 3"
    PK3["PK: C2"] --> C4
    PK3 --> C5
    PK3 --> C7
    end

    subgraph "Table 4"
    PK4["PK: C7"] --> C6
    end